services:
  django:
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  ghi:
    image: node:20.11.1
    build:
      context: /ghi/frontend
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_DJANGO_API: ${REACT_APP_DJANGO_API}