# Generated by Django 4.2.1 on 2023-05-25 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("started_on", models.DateField(null=True)),
                (
                    "class_count",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "class_available",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "outing_count",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "outing_available",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="client",
                        to="tracker.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="WeeklyClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_and_time", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="OutingInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                ("starts", models.DateTimeField()),
                ("ends", models.DateTimeField()),
                ("groups_invited", models.ManyToManyField(to="tracker.group")),
                (
                    "outing_attendance",
                    models.ManyToManyField(blank=True, to="tracker.dog"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dog",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="group",
                to="tracker.group",
            ),
        ),
        migrations.AddField(
            model_name="dog",
            name="w_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="w_class",
                to="tracker.weeklyclass",
            ),
        ),
        migrations.CreateModel(
            name="ClassInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occurred_on", models.DateTimeField(null=True)),
                ("class_attendance", models.ManyToManyField(to="tracker.dog")),
                (
                    "weekly_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weekly_class",
                        to="tracker.weeklyclass",
                    ),
                ),
            ],
        ),
    ]
