# Generated by Django 4.2.1 on 2023-05-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classinstance",
            name="class_attendance",
            field=models.ManyToManyField(blank=True, to="tracker.dog"),
        ),
        migrations.AlterField(
            model_name="classinstance",
            name="occurred_on",
            field=models.DateField(null=True),
        ),
    ]
