# Generated by Django 4.2.1 on 2023-05-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0003_dog_class_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="outing_log",
            field=models.TextField(null=True),
        ),
    ]
