# Generated by Django 4.2.1 on 2023-05-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0005_alter_dog_started_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
            ],
        ),
    ]
