# Generated by Django 4.2.1 on 2023-06-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0010_alter_outinginstance_attendance_taken"),
    ]

    operations = [
        migrations.AddField(
            model_name="outinginstance",
            name="address",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
