# Generated by Django 4.2.1 on 2023-12-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0015_alter_client_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
