# Generated by Django 4.2.1 on 2023-12-20 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0016_dog_archived"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dog",
            name="class_log",
        ),
        migrations.RemoveField(
            model_name="dog",
            name="outing_log",
        ),
        migrations.RemoveField(
            model_name="dog",
            name="pvt_log",
        ),
        migrations.AlterField(
            model_name="pvtpackage",
            name="dog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tracker.dog"
            ),
        ),
    ]
