# Generated by Django 4.2.1 on 2023-06-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0006_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="outinginstance",
            name="attendance_taken",
            field=models.BooleanField(default=False),
        ),
    ]
