# Generated by Django 4.2.1 on 2023-06-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0009_alter_outinginstance_attendance_taken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outinginstance",
            name="attendance_taken",
            field=models.BooleanField(default=False),
        ),
    ]
