# Generated by Django 4.2.1 on 2023-06-11 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0012_notes_date_added_notes_is_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="pvt_avail",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="dog",
            name="pvt_count",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="dog",
            name="pvt_log",
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name="PvtPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sessions", models.IntegerField()),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dog",
                        to="tracker.dog",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PvtInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occurred_on", models.DateField(null=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package",
                        to="tracker.pvtpackage",
                    ),
                ),
            ],
        ),
    ]
