# Generated by Django 4.2.1 on 2023-12-20 02:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0017_remove_dog_class_log_remove_dog_outing_log_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dog",
            name="class_count",
        ),
        migrations.RemoveField(
            model_name="dog",
            name="outing_count",
        ),
        migrations.RemoveField(
            model_name="dog",
            name="pvt_avail",
        ),
        migrations.RemoveField(
            model_name="dog",
            name="pvt_count",
        ),
    ]
